---
# Remove sync_gateway
- hosts: sync_gateways:sg_accels

  tasks:
  - include: tasks/remove-sync-gateway.yml
    when: ansible_distribution == "CentOS"

  - include: tasks/remove-sync-gateway-windows.yml
    when: ansible_os_family == "Windows"

  - include: tasks/remove-sg-accel.yml
    when: ansible_distribution == "CentOS"

  - include: tasks/clean-users.yml
    when: ansible_distribution == "CentOS"

  # Check no sync_gateways or accels running
  - name: SYNC GATEWAY | verify no service on 4985
    wait_for: port=4985 delay=1 state=stopped
    when: ansible_distribution == "CentOS"

# Flush server buckets
- hosts: couchbase_servers
  any_errors_fatal: true
  vars:
    # Primary node
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"

    # Current node
    couchbase_server_node: "{{ hostvars[inventory_hostname]['ansible_host'] }}"

    couchbase_server_home_path: /opt/couchbase
    couchbase_server_admin_port: 8091
    couchbase_server_admin: Administrator
    couchbase_server_password: password

    couchbase_server_bucket_type: couchbase
    couchbase_server_bucket_replica: 1
    couchbase_server_cluster_ram: "{{ ((ansible_memtotal_mb|int)*0.8)|int - 512 }}"
    couchbase_server_bucket_ram: "{{ ((couchbase_server_cluster_ram|int)*0.5)|int }}"

# Create sync_gateway user
- hosts: sync_gateways
  any_errors_fatal: true
  tasks:
  - include: tasks/create-sync-gateway-user.yml
    when: ansible_distribution == "CentOS"

# Create sg_accel user
- hosts: sg_accels
  any_errors_fatal: true
  tasks:
  - include: tasks/create-sg-accel-user.yml
    when: ansible_distribution == "CentOS"

# Download sync_gateway package
- hosts: sync_gateways
  any_errors_fatal: true

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sync_gateway_package:
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"

  tasks:
  - name: SYNC GATEWAY |  Download sync_gateway rpm {{ couchbase_sync_gateway_package_url }}
    get_url: url={{ couchbase_sync_gateway_package_url }} dest=/tmp/{{ couchbase_sync_gateway_package }}
    when: ansible_distribution == "CentOS"

  - name: SYNC GATEWAY |  Download sync_gateway exe
    {{ couchbase_sync_gateway_package | regex_replace('rpm', 'exe') }}
    couchbase_sync_gateway_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sync_gateway_package }}"
    win_get_url: url={{ couchbase_sync_gateway_package_url }} dest=C:\Users\Administrator\AppData\Local\Temp\{{ couchbase_sync_gateway_package }}
    when: ansible_os_family == "Windows"

# Download sg accel package
- hosts: sg_accels
  any_errors_fatal: true

  vars:
    couchbase_sync_gateway_package_base_url:
    couchbase_sg_accel_package:
    couchbase_sg_accel_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sg_accel_package }}"
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"

  tasks:
  - name: SYNC GATEWAY | Download sg_accel rpm {{ couchbase_sg_accel_package_url }}
    get_url: url={{ couchbase_sg_accel_package_url }} dest=/tmp/{{ couchbase_sg_accel_package }}
    when: ansible_distribution == "CentOS"

  - name: SYNC GATEWAY | Download sg_accel exe
    {{ couchbase_sg_accel_package | regex_replace('rpm', 'exe') }}
    couchbase_sg_accel_package_url: "{{ couchbase_sync_gateway_package_base_url }}/{{ couchbase_sg_accel_package }}"
    win_get_url: url={{ couchbase_sg_accel_package_url }} dest=/tmp/{{ couchbase_sg_accel_package }}
    when: ansible_os_family == "Windows"

# Deploy non writer sync_gateway configs
- hosts: sync_gateways
  any_errors_fatal: true
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    is_index_writer: "false"
  tasks:
  - include: tasks/deploy-sync-gateway-config.yml

# Deploy sg_accel index writer configs
- hosts: sg_accels
  vars:
    sync_gateway_config_filepath:
    couchbase_server_primary_node: "{{ hostvars[groups.couchbase_servers[0]].ansible_host }}"
    # hack until mobile-testkit/issues/406 allows any sync gateway to be referenced
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"
    is_index_writer: "true"
  tasks:
  - include: tasks/deploy-sg-accel-config.yml

# Install and launch sync_gateway service
- hosts: sync_gateways
  any_errors_fatal: true
  become: yes
  tasks:
  # Install and start service
  - name: SYNC GATEWAY | Install sync_gateway rpm
    shell: rpm -i /tmp/{{ couchbase_sync_gateway_package }}
    when: ansible_distribution == "CentOS"

  - name: SYNC GATEWAY | wait until sync gateway to listen on port
    wait_for: port=4985 timeout=120
    when: ansible_distribution == "CentOS"

# Install and launch sg_accel service
- hosts: sg_accels
  any_errors_fatal: true
  become: yes
  tasks:
  # Install and start service
  - name: SYNC GATEWAY | Install sg_accel rpm
    shell: rpm -i /tmp/{{ couchbase_sg_accel_package }}
    when: ansible_distribution == "CentOS"

  - name: SYNC GATEWAY | Start the service
    service: name=sg_accel state=started
    when: ansible_distribution == "CentOS"

  - name: SYNC GATEWAY | wait for sg_accel to listen on port
    wait_for: port=4985 delay=2 timeout=120
    when: ansible_distribution == "CentOS"
