- name: Windows - Install dependencies for LiteServ Windows
  hosts: windows
  vars:

  tasks:
    - name: Install nssm (https://nssm.cc/)
      win_chocolatey: name=nssm

    - name: Install VS2015 C++ Runtime
      win_chocolatey: name=vcredist2015
