---
- hosts: load_generators
  any_errors_fatal: true

  # Kill gateload
  tasks:
  - name: kill previous sgload screen
    shell: screen -X -S sgload kill
    ignore_errors: yes
  - name: kill previous sgload_expvars screen
    shell: screen -X -S sgload_expvars kill
    ignore_errors: yes


- hosts: load_generators
  any_errors_fatal: true
  become: yes
  vars:
    sync_gateway_node: "{{ hostvars[groups.sync_gateways[0]].ansible_host }}"

  # Deploy sgload script and start it
  tasks:
    - debug: msg={{ sync_gateway_node }}
    - name: copy the run sgload script
      copy: src=files/run_sgload.sh dest=/home/centos/ owner=centos group=centos mode=0755
    - name: start sgload in screen
      shell: screen -d -m -S sgload ./run_sgload.sh "http://{{ sync_gateway_node }}:4984/db/" chdir=/home/centos/
      args:
        chdir: /home/centos/



