# Add sync_gateway user
- name: SYNC GATEWAY | Create sync gateway user
  user: name=sync_gateway createhome=yes

# Add tmp logging dir (Log Rotation testing)
- name: SYNC GATEWAY | Create /tmp/sg_logs
  file:
    path: /tmp/sg_logs
    state: directory
    owner: sync_gateway
    group: sync_gateway
    mode: 0777
