# Delete logs and .pindex files
- name: SYNC GATEWAY | Delete sync_gateway logs on Windows
  become: no
  win_file:
    path: C:\PROGRA~2\Couchbase\var\lib\couchbase\logs\sync_gateway_error.log
    state: absent