# Fetch sync gateway logs for CentOS
- name: SYNC GATEWAY | Fetch sync_gateway logs
  become: yes
  # Do not validate checksum as this is just a passive grab of the logs. Since they are continuously being appended to, the checksum may fail
  fetch: src=/home/sync_gateway/logs/sync_gateway_access.log dest=/tmp/sg_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no
  fetch: src=/home/sync_gateway/logs/sync_gateway_error.log dest=/tmp/sg_logs/{{ inventory_hostname }}/ fail_on_missing=yes flat=yes validate_checksum=no