# Stop sync_gateway service
- name: SG ACCEL | Stop sg_accel service
  become: yes
  service: name=sg_accel state=stopped
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  ignore_errors: yes

- name: SG ACCEL | Stop sg_accel for CentOS 6
  become: yes
  shell: /sbin/initctl stop sg_accel
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "6"
  ignore_errors: yes

# Remove sg_accel package
- name: SG ACCEL | Uninstall sg_accel rpm
  become: yes
  shell: rpm -e couchbase-sg-accel
  ignore_errors: yes

# Remove sg_accel service
- name: SG ACCEL | Remove sg_accel service
  become: yes
  file: path=/usr/lib/systemd/system/sg_accel.service state=absent
  ignore_errors: yes

# Delete sg_accel binary
- name: SG ACCEL | Delete sg_accel binary
  become: yes
  file: path=/opt/couchbase-sg-accel state=absent
  ignore_errors: yes

# Remove sg accel source
- name: SG ACCEL | Remove sg accel source
  become: yes
  shell: rm -rf /home/centos/*
  ignore_errors: yes

- name: SG ACCEL | Remove sg accel source .repo directory
  become: yes
  shell: rm -rf /home/centos/.repo
  ignore_errors: yes

- name: SG ACCEL | Remove tmp logging dir (log rotation tests)
  become: yes
  shell: rm -rf /tmp/sg_logs
  ignore_errors: yes